#!/usr/bin/env python3
"""
Generate the Central `clubs` + `club_team_aliases` seed from adesa80-web's logoMap.js.

Why: the web resolves team logos client-side via src/lib/logoMap.js (ordered
substring patterns -> /logos/<file>). We port that mapping into the Central DB
(reusing the existing clubs + club_team_aliases tables) so logos live in the DB
and can be linked to teams. `club_team_aliases.priority` reproduces logoMap's
order-sensitivity (earlier pattern = higher priority = wins on overlap).

Output: sql/004_seed_clubs_logos.sql  (idempotent; safe to re-run).
Run:    python scripts/gen_clubs_seed.py
Then apply the generated SQL on Central (fab-cadiz-central).
"""

from __future__ import annotations

import re
from pathlib import Path

LOGOMAP_JS = Path(r"C:/Users/ferna/adesa80-web/src/lib/logoMap.js")
OUT_SQL = Path(__file__).resolve().parent.parent / "sql" / "004_seed_clubs_logos.sql"

BUCKET_BASE = "https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos"

# Curated display names per file-slug (web shows the real match name; this is a fallback).
NAMES = {
    "ubjerez": "UB Jerez",
    "gymnastica": "Gymnástica Portuense",
    "cbportuense": "CB Portuense",
    "cbsanfernando": "CB San Fernando",
    "sanroque": "CB San Roque",
    "cbgades": "CB Gades",
    "cbciudaddecadiz": "CB Ciudad de Cádiz",
    "admarianistas": "AD Marianistas",
    "cdmergablo": "CD Mergablo",
    "chipionacb": "Chipiona CB",
    "puertoreal": "CB Puerto Real",
    "cbmedinasidonia": "CB Medina Sidonia",
    "candray": "SD Candray",
    "cabu": "CABU Ubrique",
    "cbcimbis": "CB Cimbis",
    "urbaluz": "Urbaluz",
    "sanfelipeneri": "San Felipe Neri",
    "adcarteia": "AD Carteia",
    "cdudeaalgeciras": "CD UDEA Algeciras",
    "cbalgeciras": "CB Algeciras",
    "arcos": "CB Arcos",
    "cbchiclana": "CB Chiclana",
    "alcaladelosgazules": "Alcalá de los Gazules",
    "cbrota": "CB Rota",
    "losbarrios": "Los Barrios",
    "cpdonbosco": "CP Don Bosco",
    "ebmvejer": "EBM Vejer",
    "xerezcd": "Xerez CD",
    "ulblinense": "ULB Linense",
    "cdbarbate": "CD Barbate",
    "cbpradodelrey": "CB Prado del Rey",
    "sanctipetri": "Sancti Petri",
    "cdmontera": "CD Montera",
    "adcalgaida": "AD Algaida",
    "gabba": "Gabba",
    "cbtrebujena": "CB Trebujena",
    "cbinmaculadaceuta": "CB Inmaculada Ceuta",
}

# ADESA is already a registered club (slug 'adesa-80'); never create a duplicate.
ADESA_FILE = "adesa80.webp"


def sqlq(s: str) -> str:
    """Single-quote a SQL string literal."""
    return "'" + s.replace("'", "''") + "'"


def parse_logomap(js: str) -> list[tuple[list[str], str]]:
    """Extract ordered [ [patterns...], 'file' ] entries from logoMap.js."""
    entries: list[tuple[list[str], str]] = []
    # Match  [ ['p1','p2'], 'file.ext' ]  (tolerant of whitespace/newlines)
    for m in re.finditer(r"\[\s*\[([^\]]*?)\]\s*,\s*'([^']+)'\s*\]", js):
        pats = re.findall(r"'([^']*)'", m.group(1))
        pats = [p for p in pats if p != ""]
        if pats:
            entries.append((pats, m.group(2)))
    return entries


def file_slug(fname: str) -> str:
    return re.sub(r"\.(webp|svg|png|jpg|jpeg)$", "", fname, flags=re.I).lower()


def main() -> None:
    js = LOGOMAP_JS.read_text(encoding="utf-8")
    entries = parse_logomap(js)

    # Compound special-case in resolveLogoFile(): 'jerez'+'bcto' -> ubjerez.webp,
    # checked BEFORE the loop -> highest priority. Represent as the substring 'jerez bcto'.
    flat: list[tuple[str, str]] = [("jerez bcto", "ubjerez.webp")]
    for pats, fname in entries:
        for p in pats:
            flat.append((p, fname))

    # Priority: earlier in logoMap order = higher number (wins on overlap).
    n = len(flat)
    # Group by file, preserving first-seen order and per-pattern priority.
    by_file: dict[str, dict] = {}
    order: list[str] = []
    for idx, (pat, fname) in enumerate(flat):
        prio = n - idx
        if fname not in by_file:
            by_file[fname] = {"patterns": [], "first_prio": prio}
            order.append(fname)
        by_file[fname]["patterns"].append((pat, prio))

    lines: list[str] = []
    lines.append("-- 004_seed_clubs_logos  (GENERATED by scripts/gen_clubs_seed.py — do not edit by hand)")
    lines.append("-- Ports adesa80-web/src/lib/logoMap.js into Central clubs + club_team_aliases.")
    lines.append("-- Opponent clubs are active=false (not scrape targets, just logo/alias holders).")
    lines.append("-- Idempotent: ON CONFLICT upserts. Safe to re-run.")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("  v_fed uuid := (SELECT id FROM federations WHERE province = 'cadiz');")
    lines.append("  v_club uuid;")
    lines.append("BEGIN")

    opp = 0
    for fname in order:
        slug = file_slug(fname)
        logo_url = f"{BUCKET_BASE}/{fname}"
        pats = by_file[fname]["patterns"]
        primary = pats[0][0]

        if fname == ADESA_FILE:
            # Existing club: only set logo_url; add 'adesa' pattern alias.
            lines.append("")
            lines.append("  -- ADESA 80 (existing club): set logo + ensure 'adesa' alias")
            lines.append(f"  UPDATE clubs SET logo_url = {sqlq(logo_url)} WHERE slug = 'adesa-80';")
            lines.append("  SELECT id INTO v_club FROM clubs WHERE slug = 'adesa-80';")
        else:
            opp += 1
            name = NAMES.get(slug, slug.replace("-", " ").title())
            lines.append("")
            lines.append(f"  -- {name}  ({fname})")
            lines.append("  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)")
            lines.append(
                f"  VALUES (v_fed, {sqlq(name)}, {sqlq(slug)}, {sqlq(primary)}, {sqlq(logo_url)}, false, '{{}}'::jsonb)"
            )
            lines.append("  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url")
            lines.append("  RETURNING id INTO v_club;")
        # Aliases (one per pattern) with priority
        for pat, prio in pats:
            is_primary = "true" if pat == primary and fname != ADESA_FILE else "false"
            lines.append(
                f"  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) "
                f"VALUES (v_club, {sqlq(pat)}, {is_primary}, {prio}) "
                f"ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;"
            )

    lines.append("END $$;")
    lines.append("")

    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_SQL}")
    print(f"Files mapped: {len(order)} (1 ADESA + {opp} opponents)")
    print(f"Total alias patterns: {len(flat)}")
    print("Logo files referenced:")
    for fname in order:
        print(f"  {fname:28s} <- {', '.join(p for p, _ in by_file[fname]['patterns'])}")


if __name__ == "__main__":
    main()
