-- 004_seed_clubs_logos  (GENERATED by scripts/gen_clubs_seed.py — do not edit by hand)
-- Ports adesa80-web/src/lib/logoMap.js into Central clubs + club_team_aliases.
-- Opponent clubs are active=false (not scrape targets, just logo/alias holders).
-- Idempotent: ON CONFLICT upserts. Safe to re-run.

DO $$
DECLARE
  v_fed uuid := (SELECT id FROM federations WHERE province = 'cadiz');
  v_club uuid;
BEGIN

  -- UB Jerez  (ubjerez.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'UB Jerez', 'ubjerez', 'jerez bcto', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/ubjerez.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'jerez bcto', true, 59) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ubjerez', false, 58) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ubj', false, 57) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'el mira', false, 56) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Gymnástica Portuense  (gymnastica.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Gymnástica Portuense', 'gymnastica', 'gymnastica', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/gymnastica.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'gymnastica', true, 55) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'gymnástica', false, 54) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Portuense  (cbportuense.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Portuense', 'cbportuense', 'portuense', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbportuense.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'portuense', true, 53) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cbp ', false, 52) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB San Fernando  (cbsanfernando.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB San Fernando', 'cbsanfernando', 'cbsfdo', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbsanfernando.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cbsfdo', true, 51) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cb san fernando', false, 50) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'san fernando', false, 49) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'maxcolchon', false, 48) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB San Roque  (sanroque.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB San Roque', 'sanroque', 'centurias', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/sanroque.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'centurias', true, 47) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ongolf', false, 46) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'san roque', false, 15) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- ADESA 80 (existing club): set logo + ensure 'adesa' alias
  UPDATE clubs SET logo_url = 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/adesa80.webp' WHERE slug = 'adesa-80';
  SELECT id INTO v_club FROM clubs WHERE slug = 'adesa-80';
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'adesa', false, 45) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Gades  (cbgades.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Gades', 'cbgades', 'gades', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbgades.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'gades', true, 44) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Ciudad de Cádiz  (cbciudaddecadiz.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Ciudad de Cádiz', 'cbciudaddecadiz', 'cbc cádiz', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbciudaddecadiz.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cbc cádiz', true, 43) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cbc cadiz', false, 42) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- AD Marianistas  (admarianistas.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'AD Marianistas', 'admarianistas', 'marianistas', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/admarianistas.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'marianistas', true, 41) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CD Mergablo  (cdmergablo.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CD Mergablo', 'cdmergablo', 'mergablo', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cdmergablo.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'mergablo', true, 40) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Chipiona CB  (chipionacb.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Chipiona CB', 'chipionacb', 'chipiona', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/chipionacb.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'chipiona', true, 39) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Puerto Real  (puertoreal.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Puerto Real', 'puertoreal', 'puerto real', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/puertoreal.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'puerto real', true, 38) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Medina Sidonia  (cbmedinasidonia.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Medina Sidonia', 'cbmedinasidonia', 'medina', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbmedinasidonia.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'medina', true, 37) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- SD Candray  (candray.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'SD Candray', 'candray', 'candray', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/candray.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'candray', true, 36) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CABU Ubrique  (cabu.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CABU Ubrique', 'cabu', 'c.a.b.u', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cabu.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'c.a.b.u', true, 35) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cabu', false, 34) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ubrique', false, 33) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Cimbis  (cbcimbis.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Cimbis', 'cbcimbis', 'cimbis', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbcimbis.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cimbis', true, 32) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Urbaluz  (urbaluz.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Urbaluz', 'urbaluz', 'urbaluz', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/urbaluz.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'urbaluz', true, 31) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'uz red', false, 30) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- San Felipe Neri  (sanfelipeneri.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'San Felipe Neri', 'sanfelipeneri', 'san felipe', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/sanfelipeneri.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'san felipe', true, 29) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'neri', false, 28) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- AD Carteia  (ADCarteia.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'AD Carteia', 'adcarteia', 'carteia', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/ADCarteia.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'carteia', true, 27) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CD UDEA Algeciras  (cdudeaalgeciras.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CD UDEA Algeciras', 'cdudeaalgeciras', 'udea', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cdudeaalgeciras.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'udea', true, 26) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Algeciras  (cbalgeciras.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Algeciras', 'cbalgeciras', 'cba', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbalgeciras.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'cba', true, 25) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'algeciras', false, 24) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Arcos  (arcos.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Arcos', 'arcos', 'arcos', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/arcos.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'arcos', true, 23) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Chiclana  (cbchiclana.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Chiclana', 'cbchiclana', 'chiclana', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbchiclana.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'chiclana', true, 22) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ituci', false, 21) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Alcalá de los Gazules  (alcaladelosgazules.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Alcalá de los Gazules', 'alcaladelosgazules', 'alcalá', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/alcaladelosgazules.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'alcalá', true, 20) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'alcala', false, 19) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'gazules', false, 18) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Rota  (cbrota.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Rota', 'cbrota', 'rota', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbrota.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'rota', true, 17) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Los Barrios  (losbarrios.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Los Barrios', 'losbarrios', 'barrios', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/losbarrios.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'barrios', true, 16) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CP Don Bosco  (cpdonbosco.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CP Don Bosco', 'cpdonbosco', 'don bosco', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cpdonbosco.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'don bosco', true, 14) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- EBM Vejer  (ebmvejer.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'EBM Vejer', 'ebmvejer', 'vejer', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/ebmvejer.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'vejer', true, 13) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Xerez CD  (xerezcd.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Xerez CD', 'xerezcd', 'xerez', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/xerezcd.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'xerez', true, 12) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- ULB Linense  (ulblinense.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'ULB Linense', 'ulblinense', 'ulb', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/ulblinense.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ulb', true, 11) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'linense', false, 10) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CD Barbate  (cdbarbate.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CD Barbate', 'cdbarbate', 'barbate', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cdbarbate.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'barbate', true, 9) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Prado del Rey  (cbpradodelrey.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Prado del Rey', 'cbpradodelrey', 'prado', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbpradodelrey.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'prado', true, 8) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Sancti Petri  (sanctipetri.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Sancti Petri', 'sanctipetri', 'sancti petri', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/sanctipetri.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'sancti petri', true, 7) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CD Montera  (cdmontera.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CD Montera', 'cdmontera', 'montera', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cdmontera.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'montera', true, 6) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- AD Algaida  (adcalgaida.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'AD Algaida', 'adcalgaida', 'algaida', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/adcalgaida.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'algaida', true, 5) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- Gabba  (Gabba.webp)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'Gabba', 'gabba', 'gabba', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/Gabba.webp', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'gabba', true, 4) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Trebujena  (cbtrebujena.svg)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Trebujena', 'cbtrebujena', 'trebujena', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbtrebujena.svg', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'trebujena', true, 3) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;

  -- CB Inmaculada Ceuta  (cbinmaculadaceuta.svg)
  INSERT INTO clubs (federation_id, name, slug, team_pattern, logo_url, active, config)
  VALUES (v_fed, 'CB Inmaculada Ceuta', 'cbinmaculadaceuta', 'inmaculada', 'https://dzpkmkqmtdzwmrynzgus.supabase.co/storage/v1/object/public/team-logos/cbinmaculadaceuta.svg', false, '{}'::jsonb)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, logo_url = EXCLUDED.logo_url
  RETURNING id INTO v_club;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'inmaculada', true, 2) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
  INSERT INTO club_team_aliases (club_id, team_name, is_primary, priority) VALUES (v_club, 'ceuta', false, 1) ON CONFLICT (club_id, team_name) DO UPDATE SET priority = EXCLUDED.priority;
END $$;
